### ISSUE TITLE
'Solver not applicable '

### ISSUE THREAD

**Issue by zhiyuliao** [yalmip/YALMIP#1047]
I am solve a linear programming in 33 bus systems. I use second order cone to change nonlinear constraints to linear constraints. I think the constraints are right. However matlab post a error :Warning: Solver not applicable (CPLEX). A part of my matlab code. Thanks in advance for anybody who can help me with this.
nb=33;
nl=32;

%% 设置约束
C=[];

%% 节点功率约束
for i=[3,4,6:16,18:20,22,23,25:31]  %(i+1)才是二分支节点 two nodes
    %Pload(i+1)和Pls(i+1)可知这些节点是[4,5,7:17,19:21,23,24,25:32]
    C=[C,(Pl(i)-I(i)^2*r(i))*b2(i)+Pr(i+1)==(Pload(i+1)-Pls(i+1))+Pl(i+1)];
    C=[C,(Ql(i)-I(i)^2*x(i))*b2(i)+Qr(i+1)==(Qload(i+1)-Qls(i+1))+Ql(i+1)];
end

%三分支节点 three nodes
C=[C,(Pl(1)-I(1)^2*r(1))*b2(1)+Pr(2)==(Pload(2)-Pls(2))+Pl(2)+Pl(18)];
C=[C,(Ql(1)-I(1)^2*r(1))*b2(1)+Qr(2)==(Qload(2)-Qls(2))+Ql(2)+Ql(18)];
C=[C,(Pl(2)-I(2)^2*r(2))*b2(2)+Pr(3)==(Pload(3)-Pls(3))+Pl(3)+Pl(22)];
C=[C,(Pl(2)-I(2)^2*r(2))*b2(2)+Qr(3)==(Pload(3)-Pls(3))+Pl(3)+Pl(22)];
C=[C,(Pl(5)-I(5)^2*r(5))*b2(5)+Pr(6)==(Pload(6)-Pls(6))+Pl(6)+Pl(25)];
C=[C,(Pl(5)-I(5)^2*r(5))*b2(5)+Qr(6)==(Pload(6)-Pls(6))+Pl(6)+Pl(25)];

%尾节点 one node
for i=[17,21,24]
    C=[C,(Pl(i)-I(i)^2*r(i))*b2(i)+Pr(i+1)==Pload(i+1)-Pls(i+1)];
    C=[C,(Ql(i)-I(i)^2*x(i))*b2(i)+Qr(i+1)==Qload(i+1)-Qls(i+1)];
end

%% 电压约束
for i=1:nl
    C=[C,V(i+1)^2==V(data1(i,1))^2-2*(Pl(i)*r(i)+Ql(i)*x(i))+(r(i)^2+x(i)^2)*I(i)^2];
end

%% 二阶锥约束(second order cone constraints)
for i=1:nl
    C=[C,V(data1(i,1))^2*I(i)^2>=Pl(i)^2+Ql(i)^2];
end

%% 电压损耗 voltage loss
for l=1:nl
    C=[C,V(l+1)-V(data1(l,1))==(Pl(l)*r(l)+Ql(l)*x(l))/U];
end

% %% distflow constraints
% for i=1:32
%     C=[C,-(1-b2(i))*M<=sqrt(V(i+1))-sqrt(V(data1(i,1)))-Vl(i),sqrt(V(i+1))-sqrt(V(data1(i,1)))-Vl(i)<=(1-b2(i))*M];
% end

%% 节点电压约束
C=[C,0.95<=V,V<=1.05];
V(22)=1;

%% 支路电流约束
C=[C,0<=I,I<=1];

%% REG active power constraints
for i=1:nb
    C=[C,0<=Pr(i),Pr(i)<=b1(i)*Prmax(i)];
end

%%REG reactive power constraints
for i=1:nb
    C=[C,0<=Qr(i),Qr(i)<=b1(i)*Qrmax(i)];
end

%% load shedding active power constraints
for i=1:nb
    C=[C,0<=Pls(i),Pls(i)<=Pload(i)];
end

%%load shedding reactive power constraints
for i=1:nb
    C=[C,0<=Qls(i),Qls(i)<=Qload(i)];
end

%% active power flow constraints
for i=1:nl
    C=[C,-Plmax(i)*b2(i)<=Pl(i),Pl(i)<=Plmax(i)*b2(i)];
end

%%reactive power flow constraints
for i=1:nl
    C=[C,-Qlmax(i)*b2(i)<=Ql(i),Ql(i)<=Plmax(i)*b2(i)];
end

%% 目标函数
objective=sum(Pls.*m+Qls.*m);

%% 求解
ops=sdpsettings('solver','cplex','verbose',0);
sol=optimize(C,objective,ops);

**Comment by johanlofberg** [comment]
impossible to answer as the code doesn't run

**Comment by zhiyuliao** [comment]
> impossible to answer as the code doesn't run

Why? Could you give me some suggestions?

**Comment by johanlofberg** [comment]
Since it cannot be run, one would have to guess what is constants and what is decision variables, and guess the signs of various constants, and then mentally construct all constraints to figure out what qould be generated. Hence impossible (more precisely not something someone would want to waste time with) to see why this isn't SOCP-representable as you claim
