### ISSUE TITLE
Wrong ordering in solvemp

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#106]
```
yalmip clear
sdpvar x1 x2 x3
F = [ 1<=x1<=1.1; 2<=x2<=2.2; x3==x1-x2 ];
cost = x1+x2+x3;
sol = solvemp(F, cost, [], [x1; x2], x3); 
full(sol{1}.Fi{1})
% this output is correct:
ans =

 1    -1

sol = solvemp(F, cost, [], [x2; x1], x3); 
full(sol{1}.Fi{1})

% this output is wrong, should be [-1, 1]:
```

**Comment by wangwendi0705** [comment]
I have some problems that I try the example "multiparametric programming" in the YALMIP, but when I use the solvemp command, I can get the same answer as the example. The result of solvemp is empty. I am sure that I have already install the MPT solver and the same code in the matlab. I think whether I use the solvemp correct. Thanks!!

**Comment by johanlofberg** [comment]
Sounds like your installation doesn't work, which you would have to check by solving problems without the use of YALMIP, and/or debug the code and see what happens in the call to mpt

**Comment by johanlofberg** [comment]
However, don't discuss that in this closed issue. Open your own discussion thread under discussions
