### ISSUE TITLE
Simulink refers to the result of binvar type

### ISSUE THREAD

**Issue by ExorcistK** [yalmip/YALMIP#1068]
My Simulink model needs an input result, which is output by an interpreted matlab function. In the function file, I use yalmip to optimize a target, and what this function needs to export is a 0-1 variable that meets my optimal target. Therefore, I use U = value (V3) to output the result. The result u observed by the oscilloscope is 0.5. At the same time, my motor waveform is also wrong, Therefore, I would like to ask whether the output u is really 0-1 brought into SIMULINK for calculation during the actual operation of Simulink model, or because the computer binary problem can not display the correct results, but this does not affect the correct operation of the model. Whether there is a way to get the real value of V3 brought into the optimization.
![image](https://user-images.githubusercontent.com/97434797/148737759-3cf0b423-e766-4066-bcf8-b24a7e5fd9c5.png)
Thank you very much for your reply

**Comment by johanlofberg** [comment]
Being 0.5 signals that the solver you have used has run into troubles, which you should see as I presume you have all displays turned on, and that you are checking all diagnostic messages...

**Comment by ExorcistK** [comment]
> 为 0.5 表示您使用的求解器遇到了问题，您应该看到，因为我认为您已打开所有显示器，并且您正在检查所有诊断消息......

I use the oscilloscope to export the output value every time. I find that there are very outrageous values. They should be integers, but they output decimals. Whether there is a way to avoid such problems or whether some specific constraints should be added will help the solver get the correct 0-1 variables. Thank you very much for your reply
![image](https://user-images.githubusercontent.com/97434797/148866719-016deaf3-8f96-4804-bba4-accc5dd6601c.png)

**Comment by johanlofberg** [comment]
As I said, your solver is failing, i.e. you are not solving the problems. What does the solver log say, and what diagnostic codes do you get.
