### ISSUE TITLE
Fail to derivate the robust counterpart 

### ISSUE THREAD

**Issue by cccjjjfff** [yalmip/YALMIP#1120]
I wrote a program in Python, which need to call matlab (yalmip) to derive the robust counter part solved by gurobi repeatedly. After hundreds of successful cyclic calls, yalmip failed to derive the robust counter part, but stuck in the following interface. I have tried many times and the same problem occured every time.

***** Starting YALMIP robustification module. *********************
 - Detected 120 uncertain variables
 - Detected 120 independent group(s) of uncertain variables
 - Eliminating uncertainty using explicit maximization of inf-norm

**Comment by johanlofberg** [comment]
Impossible to answer without reproducible code as we don't know what is happening. A guess is that the problem is so large that it simply takes forever to construct or derive the robust counterpart (although explicit inf-norm should be quick).

**Comment by cccjjjfff** [comment]
Thanks for your patience. The program described above is as follows:

(1) There are 100 robust optimization problems with the same scale in each cycle (which can also be understood as 100 steps in each cycle). The program starts to derive the robust counter part of the next problem only after the previous problem is successfully solved by gurobi;

(2) In different cycles, the robust optimization problem corresponding to the same step is exactly the same (in other words, the No.X problem in the first, second or third cycles is exactly the same), that is, the stuck problem has been successfully solved in the previous cycles.

**Comment by johanlofberg** [comment]
That is of absolutely no help. To give any sensible answer, you would have to supply minimal reproducible code that triggers the stall.
