### ISSUE TITLE
Yalmip incorrectly determines equality constraints to be trivially true

### ISSUE THREAD

**Issue by alastair-abbott** [yalmip/YALMIP#1170]
There appears to be a bug in how yalmip determines equality constraints to be trivially true.

For example:

```
>> a = sdpvar(1); optimize([a,0] == [a,1],0)
Warning: Equality constraint evaluated to trivial true. 
> In constraint (line 45)
In  ==  (line 13) 
```

When the constraint is clearly trivially false, not true.

The error appears to be on line 44 of constraint.m. It should check
`all(Z == 0)`
rather than
`all(Z) == 0`

**Comment by johanlofberg** [comment]
Right, thanks.
