### ISSUE TITLE
Slicing problem with matrix variables

### ISSUE THREAD

**Issue by egidioln** [yalmip/YALMIP#1177]
Hello!

Using [extras/@lmi/linearize.m](https://github.com/yalmip/YALMIP/blob/e97d7e71a5e2d21b5a63d7e9f91055cbd75f89a6/extras/@lmi/linearize.m) I got an error resulting from a bad slicing of some polynomial matrix variables. I am able to reproduce this error with the following code
```
clear x
x = sdpvar(2,1);
assign(x,ones(2,1));
linearize(x*x')
```

which errors as
```
Error using  *  (line 617)
Inner matrix dimensions must agree.

Error in sdpvar/linearize (line 31)
        plin = [plin p0(:,i)+double(jacobian(p(:,i),x))*(x-x0)];
```

I fixed the `linearize` function with this workaround https://github.com/egidioln/YALMIP/commit/dc70e37d79e159af7947791dc639b127798d0bf7  but as the main problem is the slicing of `p(:,i)` (which very weirdly return `p` without slicing) I hesitate to open a PR for this. I tried tracking down the source of the real problem but I confess I am a bit clueless...

Best regards,

**Comment by johanlofberg** [comment]
Slicing inside a method can fail and not call the overloaded method, so it could be that it should be replaced with an explicit call to subsref as in subsref(p,struct('type','()',...Really messy but needed for some reason on some places

**Comment by egidioln** [comment]
Thanks for the reply!

I implemented your suggestion and it works well but it's slightly slower than the fix in my commit (as the current code performs `n` calls to `jacobian` and my workaround performs only one). Also I personally think that using `subsref` makes the code less readable. 

Do you think it's worth opening a PR?

**Comment by johanlofberg** [comment]
Your fix appears sound, so test it a bit on other dimensions on variables and functions just to avoid any silly regression. If you really want to be fancy, add a test in dev/tests/core (copy-paste from something like test_sdpvar_mtimes) as I've never did that. After designing the test, you can test it locally by simply pressing the Run tests icon in the header in MATLAB

**Comment by johanlofberg** [comment]
take the opportunity to change double to value too when you're in there
