### ISSUE TITLE
scs.eps option obsolete

### ISSUE THREAD

**Issue by alastair-abbott** [yalmip/YALMIP#1183]
Scs removed the 'eps' option and replaced it by 3 others around version 2.2.0 (now at 3.2.0):
eps_abs, eps_rel, and eps_infeas

The default sdpsettings should be updated accordingly, potentially keeping scs.eps for backwards compatibility (recent versions of scs simply ignore it)

**Comment by araujoms** [comment]
Thanks for posting this issue, I was trying to understand why `scs.eps` wasn't working.
