### ISSUE TITLE
How can I reconstruct a sparse matrix?

### ISSUE THREAD

**Issue by KarryMa** [yalmip/YALMIP#1190]
Can I minimize $l_1$  norm to reconstruct a sparse matrix, but the way, how can I know a matrix is sparse matrix ?

**Comment by KarryMa** [comment]
I don't know if a matrix is sparse that means I have a matrix like this 
![image](https://user-images.githubusercontent.com/53418276/197188794-dd17a783-d9c0-4e2c-b78a-c0ae586910ad.png)
Can I say it is a sparse matrix? And If I have a 16*16 matrix with 28 non-zero elements, can I say it is sparse, and use $l_1$ norm to reconstruct it?

**Comment by johanlofberg** [comment]
Weird question. It is like asking if you can call the matrix small. It is obviously sparser than a full matrix, but still 6/16 elements are non-zero. If that is  sparse for you, is up to you to decide

Question regarding reconstruction is also strange, as we don't know what you mean with reconstruct, from what, or where you intend to use l1 norm or anything.
