### ISSUE TITLE
Should yalmip("version") return "20230609"?

### ISSUE THREAD

**Issue by robertgj** [yalmip/YALMIP#1296]
Thanks very much for updating YALMIP. 

This feels rather pedantic but the release version in yalmip.m doesn't match the version on the github releases page:
diff --git a/extras/yalmip.m b/extras/yalmip.m
index de378042..83e25de2 100644
--- a/extras/yalmip.m
+++ b/extras/yalmip.m
@@ -1035,7 +1035,7 @@ switch varargin{1}
         
         
     case {'version','ver'}
-        varargout{1} = '20210609';
+        varargout{1} = '20230609';
         
     case 'setintvariables'
         internal_sdpvarstate.intVariables = varargin{2};

**Comment by johanlofberg** [comment]
Yes, I saw that too, it will be fixed in the new release in a couple of days
