### ISSUE TITLE
Pseudo-Expectations in duals of SOS programs should be supported

### ISSUE THREAD

**Issue by sarthak-choudhary** [yalmip/YALMIP#1311]
Problem: As pseudo-distributions are duals of sum-of-squares programs, in many algorithms, it's easy to define the constraints in terms of dual variables i.e. Pseudo-Expectations of primal variables. Therefore, there should be an implementation of pseudo expectation operator in the package which can be helpful for developing many algorithms.
You can refer to more details [here](https://www.sumofsquares.org/public/lec01-2_definitions.html#sec-pseudo-distributions).

**Comment by sarthak-choudhary** [comment]
I was trying to implement an SOS algorithm and implemented the pseudo-expectation operator for the package. Please assign this issue to me @johanlofberg.

**Comment by johanlofberg** [comment]
isn't this just moments https://yalmip.github.io/tutorial/momentrelaxations/ which is the dual of sos
