### ISSUE TITLE
Default value set out of bound.

### ISSUE THREAD

**Issue by eshoubak** [yalmip/YALMIP#1376]
I was getting some different behavior recently with yalmip//gurobi.

A model that ran fine in the past is throwing this error (output of optimize in matlab from repl):

--------------------------------------------------------------------------------------------------------------
sol_up = 

  struct with fields:

    yalmipversion: '20230622'
    matlabversion: '23.2.0.2459199 (R2023b) Update 5'
       yalmiptime: NaN
       solvertime: NaN
             info: 'Unknown problem (learn to debug) (Unknown problem (learn to debug) (Error using gurobi↵Gurobi error 10008: Unable to set parameter TuneTimeLimit to value -1 (minimum is 0)↵))'
          problem: 9
-------------------------------------------------------------------------------------------------------------

So I added:
options_up.gurobi.TuneTimeLimit = 0;
 
to optimizer options and now things seem to work again.

I am puzzled because this is new behavior that I am not sure if its due to yalmip or gurobi, seemingly setting a default value out of bounds.

**Comment by johanlofberg** [comment]
Fixed in #1358
