### ISSUE TITLE
solvesdp() uses set(...)

### ISSUE THREAD

**Issue by kvasnica** [yalmip/YALMIP#212]
``` matlab
sdpvar x u; solvesdp([x==0 | u==0], [])
```

```
Error using constraint/set (line 6)
Obsolete command

Error in solvesdp (line 92)
            Fnew = Fnew + set(true(F(i)));
```

**Comment by sqsun** [comment]
have you solve your problem?

**Comment by sqsun** [comment]
@kvasnica

**Comment by johanlofberg** [comment]
this was fixed long time ago

**Comment by sqsun** [comment]
I met the same problem. But i donot know how to solve?

**Comment by johanlofberg** [comment]
use the last version of yalmip

**Comment by sqsun** [comment]
It remind me this.  Why? Undefined function 'optimize' for input arguments of type 'lmi'.

**Comment by johanlofberg** [comment]
As I said, use the last version of YALMIP. You appear to be using a very old version.

**Comment by Douglas-Bizarro** [comment]
Hello, I have a similar issue.

A tutorial instructs to use the command: "Restr = set(P > 0) + set(A’*P+P*A < 0);". however, looks like "set" is obsolete.

How can I set theese restrictions?

Thanks.

**Comment by Douglas-Bizarro** [comment]
Thank you, @johanlofberg .
