### ISSUE TITLE
Bugfix: Tutorial on Rank constrained SDP

### ISSUE THREAD

**Issue by cahans** [yalmip/YALMIP#394]
On https://yalmip.github.io/tutorial/ranksdp/, it should be 

````matlab
optimize(F,[],sdpsettings('lmirank.solver','sedumi','sedumi.eps',0))
````

Note that these computations only give a feasible pair **X** and **Y**. To actually compute the controller (called reconstruction) requires some additional steps. 

If we compute the eigenvalues of our rank constrained matrix, we immediately see that we effectively have a rank of 6.

````matlab
eig(value([X eye(4);eye(4) Y]))
ans =
   -0.0000
   -0.0000
    1.6780
    2.5342
    2.7754
    2.9674
    6.2289
    6.8932
````

**Comment by johanlofberg** [comment]
Thanks!
