### ISSUE TITLE
SeDuMi default options overriden

### ISSUE THREAD

**Issue by denisrosset** [yalmip/YALMIP#395]
I had a look at the default parameter values in sdpsettings. Some of them are not initialized to the SeDuMi 1.1 defaults (from http://sedumi.ie.lehigh.edu/sedumi/files/sedumi-downloads/SeDuMi_Guide_11.pdf).

Either the default settings should be made consistent, or the particular choice of these parameters should be documented. For example `cg.qprec = 0` leads to higher incidence of numerical errors in one of my test cases.

I noticed the following differences:

Parameter SeDuMi / Yalmip default

pars.eps 1e-8 1e-9

pars.stepdif 2 0

pars.sdp 1 0

pars.mu NA 1.0

pars.chol.maxu NA 5e5

pars.cg.maxiter 49 25

pars.cg.qprec 1 0

pars.maxradius NA inf

**Comment by johanlofberg** [comment]
Yes. I do not dare to change these values though, 15 years of code out in the wild so better keep it as it's always been.

**Comment by denisrosset** [comment]
Completely understand! Should I submit a PR against https://github.com/yalmip/yalmip.github.io/blob/master/_posts/solvers/2016-09-17-sedumi.md ? 

Is it enough to add some info in markdown format there?

**Comment by johanlofberg** [comment]
You're welcome to add that info

**Comment by denisrosset** [comment]
Note: added the info.
