### ISSUE TITLE
double-sided constraint with nd-array

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#398]
Doesn't work

    K>> sdpvar(2,3,4) <= 0 <= sdpvar(2,3,4)
    Undefined function 'gethackflag' for input arguments of type 'ndsdpvar'.

**Comment by PiotrBalik** [comment]
Since `gethackflag` is solved, there is another problem, when `getbase` of nsdpvar returns sdpvar vector.

Simply changing
```matlab
extras/@lmi/lmi.m/203
B = getbase(thisFi);
````
to
```matlab
B = getbase(thisFi(:));
````
fixes this issue. Safe to request?
