### ISSUE TITLE
SET is obsolete

### ISSUE THREAD

**Issue by VukVukovic** [yalmip/YALMIP#439]
I want to use Matlab library PPTMixer whose requirement is Yalimp. I am getting the error "SET has been considered obsolete for many years, and the time has come... Update your code. http://users.isy.liu.se/johanl/yalmip/pmwiki.php?n=Commands.set". However, the following link does not work. Which changes should I make to the PPTMixer's code for it to start working?

Here is one of the examples of set which I found in its code:
`constr=constr+set(P{m}>=0,strcat('Positive semidefiniteness of P_M where M={', num2str(find(Mvec)),'}'));`

**Comment by johanlofberg** [comment]
https://yalmip.github.io/tutorial/basics/

constr=[constr ,P{m}>=0]

if you can live without the string tags

**Comment by hanselliu** [comment]
I have the same problem with PPTMixer. How did you fix it, change the PPTMixer or use the old release? Which kind of the  release is suitable?
