### ISSUE TITLE
Missing support for CPLEX 12.8 dealing with SOCP problems.

### ISSUE THREAD

**Issue by t1393988511** [yalmip/YALMIP#464]
Recent commit 97e1e7a https://github.com/yalmip/YALMIP/commit/97e1e7a2bf2a0a7e256f0625cba351765ccf5244 added support for CPLEX 12.8. However, only support for cplex as a QP solver is added. Seems like missing the following codes in solvers/definesolvers.m.

solver(i) = qpsolver;
solver(i).tag     = 'CPLEX';
solver(i).version = 'IBM';
solver(i).subversion = '12.8.0';
solver(i).checkfor= {'cplexqcp.m','cplexlink1280'};
solver(i).call    = 'call_cplexibm_qcmiqp';
solver(i).objective.quadratic.convex = 1;
solver(i).constraint.inequalities.elementwise.quadratic.convex = 1;
solver(i).constraint.inequalities.secondordercone.linear = 1;
solver(i).constraint.integer = 1;
solver(i).constraint.binary = 1;
solver(i).constraint.sos2 = 1;
solver(i).constraint.semivar = 1;
solver(i).constraint.semiintvar = 1;
solver(i).supportsinitial = 1;
i = i+1;

**Comment by johanlofberg** [comment]
OK.

I'll try to ship a new release next week and will include this. 

Are you running cplex 12.8 with MATLAB 2016 or 2017? Is it 100% stable? Could you try to edit sdpsettings.m and the subfunction and remove the initial check for versions and use
`   
        cplex = cplexoptimset('cplex');
      
and see if it runs without crashing every now and then as it has been doing with 12.6 and 12.7

**Comment by t1393988511** [comment]
Having MATLAB R2017b and CPLEX 12.7.1&12.8 installed on my laptop.
In my previous environment (2017b+12.7.1), MATLAB crashed ocassionally, but not every time, when 'cplex = cplexoptimset('cplex');' is called. 
I tested it on the 2017b+12.8 environment just right now with the following code. It didn't crash. But that cannot prove IBM has fixed that bug.

for i = 1:100
    x = randn(1000);
    n = ceil(10*rand(1));
    m = ceil(10*rand(1));
    cplexops = cplexoptimset('cplex');
    [x,fval,exitflag,output,lambda] = cplexlp(randn(n,1),randn(m,n),rand(m,1),randn(m,n),rand(m,1),[],[],[],cplexops);
end

I'll continue with the new environment in the following days and keep you informed once thewre is a crash.

**Comment by johanlofberg** [comment]
OK. If you are using yalmip, use the unprotected version in sdpsettings, as that will give a lot of calls to cplexoptimset with different memory situations, increasing likelihood for a crash. I cannot have cplex in my path as cplexoptimset is called everytime sdpsettings is called, it crashes randomly, but if I try to trigger it with a for-loop similar to the one you have above, it never crashes
