### ISSUE TITLE
Defining operators in packages is not supported

### ISSUE THREAD

**Issue by denisrosset** [yalmip/YALMIP#477]
I'm using Matlab packages to avoid name collisions in a library I'm writing. The library has support for both YALMIP and CVX. However, I cannot put new nonlinear operators in the package, as it conflicts with YALMIP's internal handling.

Steps to reproduce:

1. Add the file `tracenorm.m` given in https://yalmip.github.io/tutorial/nonlinearoperatorsgraphs/ in a subfolder `+samplepkg` of the current folder
  Note:  a `[` is missing in the line `F = [[A X;X' B] >= 0, trace(A)+trace(B) <= 2*t];`
2. Run the following script:

```matlab 
X = sdpvar(4, 4)
optimize(X >= 0, samplepkg.tracenorm(X))
```
The output given below. Note that YALMIP does not handle operators defined in (static) methods of classes, but CVX does not either, so I already had to abandon that idea.

```
Error using sdpvar/model (line 66)
Failed when trying to create a model for the "tracenorm" operator

Error in expandrecursive (line 19)
    [properties,F_graph,arguments,fcn] = model(variable,method,options,allExtStruct(ext_index),w);

Error in expandmodel>expand (line 416)
            [F_expand,failure,cause] =
            expandrecursive(recover(variables(i)),F_expand,extendedvariables,monomtable,variabletype,where,level+1,options,method,[],'convex',allExtStruct,w);
            
Error in expandmodel (line 248)
    [F_expand,failure,cause] =
    expand(index_in_extended,variables,h,F_expand,extendedvariables,monomtable,variabletype,'objective',0,options,method,[],allExtStructs,w);
    
Error in compileinterfacedata (line 116)
    [F,failure,cause,operators] = expandmodel(F,h,options);

Error in solvesdp (line 231)
[interfacedata,recoverdata,solver,diagnostic,F,Fremoved,ForiginalQuadratics] =
compileinterfacedata(F,[],logdetStruct,h,options,0,solving_parametric);

Error in optimize (line 31)
[varargout{1:nargout}] = solvesdp(varargin{:});
```

**Comment by johanlofberg** [comment]
This is a bit beyond me, as I'm stuck in the old class definitions for compatibility, so I've never bother to learn about this

Changing the last line in tracenorm to explicitly include samplepkg works here

`varargout{1} = yalmip('define','samplepkg.tracenorm',varargin{:}); `

**Comment by denisrosset** [comment]
Thanks, that's fantastic. Testing it out and will submit a PR for the documentation to include that workaround.

**Comment by denisrosset** [comment]
Note: I did not find a simple place to add that comment in the docs, as `yalmip('define', ...)` is not documented as a command (and I don't feel like adding this very specific case in the 3 tutorials about callbacks, graph representations and so on. Thanks for your help!
