### ISSUE TITLE
Support for SSOS/DSOS/SDSOS optimization

### ISSUE THREAD

**Issue by htadashi** [yalmip/YALMIP#505]
Hi Johan,

First of all, thanks for developing and maintaining YALMIP without charge. The use of YALMIP helped me a lot in my research, and I think many others researchers are also in debt to you. 

I am writing this issue to ask if there are any plans to add support for [SSOS](https://arxiv.org/abs/1807.05463) and/or [DSOS/SDSOS](https://arxiv.org/abs/1706.02586) optimization hierarchies? 

Best regards

**Comment by johanlofberg** [comment]
I actually already played around a bit with that some years ago, but never made anything official

From the code, the options sos.model
    % 2=Image model, 4=reduced nonlinear, 5=dd,6=sd

It has not been tested much...
