### ISSUE TITLE
How the yalmip('setsolution',**) works

### ISSUE THREAD

**Issue by Simona787** [yalmip/YALMIP#506]
Hi Johan,
 Recently I have done some works about solving  sdp problems,and it's very kind for you to offer such a great modelling toolkit . Thanks a lot.
And here I would like to know some details about how the outputs derived from the sdp solvers are used to recover the final solution. I followed the source codes and found that final value of the constraints matrix F and target function h are set after executing the `yalmip('setsolution',solution_internal);` ,but when I went to the source codes of this line, nothing could be found directly related to the value changing of F and h. So, I wonder if it is convenient for you to tell me what  happened here, or anything I missed.

the two pictures show some related source codes, 
![p1](https://user-images.githubusercontent.com/17819275/43243152-b3ac1100-90d7-11e8-8325-34d3253916c3.png)
![p2](https://user-images.githubusercontent.com/17819275/43243157-b8fc3cde-90d7-11e8-987e-cadb371ec1d3.png)

**Comment by johanlofberg** [comment]
Not sure why you are in there poking around at this level. setsolution stores the values of the variables, the constraints and all other epressions are then functions of the variables, automatically computed when needed.

**Comment by johanlofberg** [comment]
I don't understand what it is you are trying to do. setsolution saves the solution, and when YALMIP needs to compute the value of a constraint for some reason (when value or check is called for instance), the expression is evaluated by asking for x from the database, and then, in the case of linear models, returning F0 + x1*F1 + x2*F2+...
