### ISSUE TITLE
QP representation of the Huber operator

### ISSUE THREAD

**Issue by gbanjac** [yalmip/YALMIP#570]
Is there a particular reason for the Huber operator to be implemented using a graph representation based on SOCP? It could also be reduced to a QP.

If I try to solve the Huber regression problem using a QP solver, I get the following warning:
```
Warning: Solver not applicable (osqp)
```

Here is a numerical example:
```
% Generate problem data
rng(1)
n = 10;
m = 100;
A = sprandn(m, n, 0.5);
x_true = randn(n, 1) / sqrt(n);
ind95 = rand(m, 1) > 0.95;
b = A*x_true + 10*rand(m, 1).*ind95 + 0.5*randn(m, 1).*(1-ind95);

% Define problem
x = sdpvar(n, 1);
objective = sum(huber(A*x - b));

% Solve with OSQP
options = sdpsettings('solver', 'osqp');
optimize([], objective, options);
```

**Comment by johanlofberg** [comment]
Yes, the framework is built using the principle f(x) is replaced with t and f(x)<=t. With huber returning a quadratic expression, it would get messier when doing convexity propagation etc

**Comment by johanlofberg** [comment]
Absolutely, completely agree, but there is currently no nice way of doing it, using the same infrastructure as the rest (well, there is, but it leads to special case treatment in the compilation, which I try to keep at a minimum)

**Comment by gbanjac** [comment]
Ok, thanks for the clarification!

**Comment by johanlofberg** [comment]
Keeping this to think about, it's something I wanted my self, so I might add some general strategy for this

**Comment by gbanjac** [comment]
That would be great! Note that [CVXPY 1.0](http://www.cvxpy.org/updates/index.html) already supports multiple reductions.

**Comment by johanlofberg** [comment]
Did a quick fix (which still is pretty general I think, will have to think about the bigger picture), checked in on develop. I think YALMIP has a lot of what cvxpy now calls multiple reductions, there's a lot of different models available for more complex operators, in particular in the nonconvex case

**Comment by johanlofberg** [comment]
and note that I saw a bug in the huber operator, so previous results are not comparable (it used to say ...+2*M*sum(v), but it should be +2*sum(M.*v)). Worked as expected on scalar terms which I had tested, but not on vectorized arguments

**Comment by johanlofberg** [comment]
note that the sum operator in your example is redundant

```
>> help huber
  huber  Returns the Hüber function (convex operator)
 
  p = huber(x,M)
 
  Returns sum_i h(x_i,M) where h(x) is the scalar Hüber function
   h(x) = x^2         if |x|<=M
          M(2*|x|-M)  otherwise
 
  The Hüber functions is convex and non-monotonic.
```
