### ISSUE TITLE
How to select "direct" or "indirect" SCS solver? 

### ISSUE THREAD

**Issue by riccardomurri** [yalmip/YALMIP#577]
Hello,

I am unable to figure out how to select the use of the "direct" or "indirect" SCS solver:

* in `callscs.m` lines 79--84, selection happens based on the `model.tag` parameter (`scs-direct` or otherwise),

_however_

* in `definesolvers.m` lines 1523--1543, both the direct and indirect flavors have tag name `scs`.

Am I missing some important detail here?

Thanks for any hint,
Riccardo

**Comment by johanlofberg** [comment]
Ah, I'll update the description in the Wiki. To use a specific version, use 'scs-direct' or 'scs-indirect'

**Comment by johanlofberg** [comment]
..and the general idea is that the short-name for a solver is solver.tag as defined in definesolvers, but when there are multiple versions etc and one needs a clarification, it is [solver.tag '-' solver.version], and this full name is the name used internally

**Comment by riccardomurri** [comment]
Thanks a lot for the quick reply, using `scs-direct` or `scs-indirect` in the `options` struct does the job.
