### ISSUE TITLE
transpose of Multi-dimensional SDPVAR object

### ISSUE THREAD

**Issue by zshn25** [yalmip/YALMIP#588]
Transpose of ndsdpvar doesn't work

`ndsdpvariable = sdpvar(3,4,2) 
Multi-dimensional SDPVAR object 3x4x2`
`ndsdpvariable' 
Multi-dimensional SDPVAR object 3x4x2`
`transpose(ndsdpvariable) 
Multi-dimensional SDPVAR object 3x4x2`

**Comment by johanlofberg** [comment]
Sorry for missing your report.

Transpose on nd-arrays is not MATLAB consistent
`>> x = randn(2,3,4);
>> x'
Error using  ' 
Transpose on ND array is not defined. Use PERMUTE instead.
 `
Having said that, permute is not support on nd-sdpvar arrays, and might be something I'll add.
