### ISSUE TITLE
Support singleton dimensions in ndsdpvars when permuting

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#590]
`>> X = sdpvar(2,3,1,1);
>> permute(X,[4 3 2 1])
Index exceeds array bounds.

Error in sdpvar/permute (line 8)
X.dim = X.dim(p);
 `

**Comment by PiotrBalik** [comment]
Fixed already in 4d91bf1dbbb4dbfba1382a75904e5dba91267e58 ?

**Comment by johanlofberg** [comment]
Yes, appears to have missed closing when  checking in fix
