### ISSUE TITLE
Support partial initial guess in CPLEX

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#591]

**Comment by bertramr** [comment]
As far as I understand the changes in `append_normalized_socp` in develop branch the `x0` is always initialized with an empty array and therefore the `if ~isempty(x0)` never is true - did not test it though.

**Comment by johanlofberg** [comment]
You mean line 5 in append_normalized_socp? Yes, that line should definitely not be kept. Looks like I've been playing around there and forgot to go back
