### ISSUE TITLE
Update Mosek geometric solver to use exponential cone

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#594]

**Comment by lukacsarpad** [comment]
As a workaround, in the meanwhile it is possible to copy the mskgpopt.m file from a previous version of MOSEK, and use MOSEK 9.

**Comment by johanlofberg** [comment]
Really? That was a surprise to me. I though they had removed the computational engine I used for GPs and that it had to be rewritten. Good to know!

**Comment by johanlofberg** [comment]
I don't think it works robustly. If you run runxunittests('xunit/geometric') you will see several failures.

I've asked Mosek about this

**Comment by johanlofberg** [comment]
It runs, but the solution computed is never the correct one, hence this cannot be used

**Comment by aszekMosek** [comment]
If it works it is only by a coincidence more unlikely than the Earth being hit by a panda bear in a pink outfit arriving in a Tesla from Mars. Please do not rely on it. The whole interface was removed in Mosek 9 and problems using it should be expressed using the conic form to the extent possible (powers, exponentials, logarithms etc.)

**Comment by johanlofberg** [comment]
Not completely impossible!
https://www-s.mlo.me/upcs/hv/tb2014/tb201409/tb20140926/88c14ffd-4b5a-4f85-85fd-07ecb78a251a.JPG

**Comment by johanlofberg** [comment]
If you use the hack checked into develop branch just now, make sure to delete the mskgpopt that you copied to Mosek 9

**Comment by johanlofberg** [comment]
Fixed in 87e6fc4
