### ISSUE TITLE
CPLEX download link doesn't work anymore

### ISSUE THREAD

**Issue by zshn25** [yalmip/YALMIP#600]
CPLEX download link from the website [https://yalmip.github.io/solver/cplex/](cplex) doesn't work. I also don't seem to find it online. Please update the download link.

**Comment by johanlofberg** [comment]
I have no idea where they've hidden it now, they try to make it as hard as possible to use. Vote with your feet by using Gurobi or mosek...

**Comment by johanlofberg** [comment]
This is my best guess https://ibm.onthehub.com/WebStore/ProductSearchOfferingList.aspx?srch=ilog%20cplex
