### ISSUE TITLE
SVD for sdpvar not defined

### ISSUE THREAD

**Issue by zshn25** [yalmip/YALMIP#613]
Hi,

SVD for an `sdpvar `variable gives error

`>> svd(sdpvar(1,1))
Error using svd
First input must be single or double.`

If it is not supported, are there alternatives for calculating SVD of a variable?

**Comment by johanlofberg** [comment]
The first question is if you actually want the SVD, or if you simply intend to compute an expression which depends on the singular values, but has representation which doesn't eplicitly require  decomposition (such as nuclear norm etc)

In general though, an SVD decmposition is not easily represented, and the only way to do it is to brute force it by introdung matrices U,V,S and add the constraints X == U*S*V', U*U'=eye(n) etc etc. Of course, an absolutely hopeless model which will fail in almost all setups

**Comment by zshn25** [comment]
Thanks for your quick reply. I am using` [U, ~, V]` to compute a rotation matrix. Are you aware of any other way to do that?

**Comment by johanlofberg** [comment]
Of course you don't, as svd(value(x)) simply applies svd on the value you assigned as the output from value is that data

The U and V matrices are nonconvex horrible operators from X, and there is no nice way to work with them explicitly in a convex way. If you want to develop some optimization model based explicitly on these, you are typically better of deriving a specialized solver, than trying to force them into a general nonlinear solver
