### ISSUE TITLE
Cannot use linspace with sdpvar

### ISSUE THREAD

**Issue by Junzeng-x14** [yalmip/YALMIP#653]
Since sdpvar doesn't have a function `isinf`, we cannot do something like `linspace(0,a,10)` when `a = sdpvar(1)` for example. Shall we introduce that function?

**Comment by johanlofberg** [comment]
linspace(0,1,10)*a would be a temporary fix. I'll think about if adding linspace operator

**Comment by Junzeng-x14** [comment]
> linspace(0,1,10)*a would be a temporary fix. I'll think about if adding linspace operator

I see! Thanks for response!

**Comment by Junzeng-x14** [comment]
I have seen your latest commit. Thank you for contributing to it!
