### ISSUE TITLE
Multiple CPU cores or threads for IPOPT

### ISSUE THREAD

**Issue by junzengx14** [yalmip/YALMIP#670]
I'm using IPOPT with Yalmip on Matlab, I'm wondering if we could use multiple CPU cores to do the optimization. Currently, only one CPU core is using during the optimization.

If not possible, could you suggest a general nonlinear optimization solver that could be used over multiple CPU with Yalmip on Matlab?

Thank you so much for your response.

**Comment by johanlofberg** [comment]
That would simply be a solver/MATLAB issue and not related to yalmip (beyond tweaking possible solver options as usual via sdpsettins)

**Comment by junzengx14** [comment]
> That would simply be a solver/MATLAB issue and not related to yalmip (beyond tweaking possible solver options as usual via sdpsettins)

OK, I thought it might be possible that we could specify `num_cpu_cores = 4` for example in the sdpsettings somewhere.

Thank for your reply.

**Comment by johanlofberg** [comment]
If the solver has such an options, you specify precisely that
