### ISSUE TITLE
Opposite dual variables acquired through YALMIP dual() using CPLEX

### ISSUE THREAD

**Issue by t1393988511** [yalmip/YALMIP#685]
It seems the dual variables acquired from the dual() function are opposite if I'm using CPLEX.

I have the latest YALMIP-R20200116_hotfix installed, not the develop branch.
The following are the solvers tested on my laptop.
- CPLEX 12.10.0
- GUROBI 9.0.0
- MOSEK 9.1
- IPOPT 3.12.9

I found that the dual() function always gives the opposite result on CPLEX compared with the other 3 solvers.

I attached a test script.
[test_dual.m.txt](https://github.com/yalmip/YALMIP/files/4176473/test_dual.m.txt)

The results are:
```
---min -x s.t. x<=1---
cplex: -1
gurobi: 1
mosek: 1
ipopt: 1
---min x s.t. x>=1---
cplex: -1
gurobi: 1
mosek: 1
ipopt: 1
---min -x s.t. x==1---
cplex: -1
gurobi: 1
mosek: 1
ipopt: 1
---min x s.t. x==1---
cplex: 1
gurobi: -1
mosek: -1
ipopt: -1
```

I believe that cplex is wrong and the other three are correct based on https://en.wikipedia.org/wiki/Duality_(optimization)

**Comment by johanlofberg** [comment]
There is no correct sign, it depends on how you define the Langrangian.

YALMIP works with non-negative duals for inequalities. For equalities, it is even less defined as you get different signs if you switch the sign of the equality (and there is no way to know if x == y will be represented as x-y==0 or y-x==0, leading to different signs)

**Comment by t1393988511** [comment]
I agree that it is hard to define dual variable signs of equality constraints.

The results I provided shows that dual variables for inequalities are not non-negative if solver is cplex (in the first two cases). And non-negative dual variables for inequalities are necessary for a minimization problem, as it is a necessary KKT condition.

From the perspective of YALMIP, it is better that its results are indepedent of solvers. In other words, users may expect that the dual variables won't change if they switched the solver from gurobi to cplex.

**Comment by johanlofberg** [comment]
It appears cplex 12.10 has switched the order then (either intentionally or there is a buf in their matlab interface, which is no surprise from their history...). YALMIP is coded to deliver consistent signs of inequality duals over all solvers

cplex 12.8
```
x = sdpvar(1);
disp('---min -x s.t. x<=1---');
con = (x<=1);
optimize(con,-x,sdpsettings('solver','cplex','verbose',0));
disp(['cplex: ',num2str(dual(con))]);
---min -x s.t. x<=1---
cplex: 1
```

**Comment by johanlofberg** [comment]
Try this in 12.10

```
[~,~,~,~,L]=cplexlp(-1,1,1)
L = 
  struct with fields:

    ineqlin: 1
      eqlin: [1×0 double]
      lower: 0
      upper: 0
```

**Comment by t1393988511** [comment]
I have the same results in 12.10
```
    ineqlin: 1
      eqlin: [1×0 double]
      lower: 0
      upper: 0
```

**Comment by johanlofberg** [comment]
Aha, now I see. There is a problem in the interpretation of version string 12.10.0, causing YALMIP to see this as the number 12.100, and in the code the dual sign is switched for version older than 12.3.

Simply remove lines 52-56 in call_cplexibm_miqp.m. I think that code will be removed as I just shouldn't support such an old version which is known to be terribly buggy

**Comment by t1393988511** [comment]
Thanks for the fix!

**Comment by yang-au-carre** [comment]
I get the same problem with cplex 12.10. So, if we want to get the correct value, we need to reverse the result given by 'dual' manually?

**Comment by johanlofberg** [comment]
Well as indicated above, this has been fixed, so I can only assume you are running an old version of cplex?

**Comment by yang-au-carre** [comment]
Thanks, I am using CPLEX 12.10.0. which I have just downloaded from the IBM website and the latest version of Yalmip as well.

**Comment by johanlofberg** [comment]
You would have to supply a minimal reproducible example, as it works here

```
sol=optimize(F,sum(x),sdpsettings('solver','cplex','savesolveroutput',1));
Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de2ae
CPXPARAM_MIP_Display                             1
Tried aggregator 1 time.
No LP presolve or aggregator reductions.
Presolve time = 0.00 sec. (0.01 ticks)

Iteration log . . .
Iteration:     1   Scaled dual infeas =             0.913329
Iteration:     4   Dual objective     =            -1.231353
>> [dual(F) sol.solveroutput.lambda.ineqlin]
ans =
         0         0
         0         0
         0         0
         0         0
    0.0402    0.0402
         0         0
    0.7661    0.7661
         0         0
         0         0
    0.4250    0.4250
```

**Comment by yang-au-carre** [comment]
> You would have to supply a minimal reproducible example, as it works here
> 
> ```
> sol=optimize(F,sum(x),sdpsettings('solver','cplex','savesolveroutput',1));
> Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de2ae
> CPXPARAM_MIP_Display                             1
> Tried aggregator 1 time.
> No LP presolve or aggregator reductions.
> Presolve time = 0.00 sec. (0.01 ticks)
> 
> Iteration log . . .
> Iteration:     1   Scaled dual infeas =             0.913329
> Iteration:     4   Dual objective     =            -1.231353
> >> [dual(F) sol.solveroutput.lambda.ineqlin]
> ans =
>          0         0
>          0         0
>          0         0
>          0         0
>     0.0402    0.0402
>          0         0
>     0.7661    0.7661
>          0         0
>          0         0
>     0.4250    0.4250
> ```
Thank you very much for the response, I tried the following example. The first dual pi1 is inversed.

%% variables
y1 = sdpvar(1,1);
y2 = sdpvar(1,1);
%% constraints
constr = [];
constr = constr + [(6*y1+10*y2 <= 2400):'eq1'];
constr = constr + [(8*y1+5*y2<=6400):'eq2'];
constr = constr + [(y1 <= 500):'eq3'];
constr = constr + [(y2 <= 100):'eq4'];
constr = constr + [0<=y1,0<=y2];
w = -24*y1-28*y2;
options=sdpsettings('solver','cplex','savesolveroutput',1);
p=optimize(constr,w,options);
% primal variable
w = value(w);
y1 = value(y1); % 400
y2 = value(y2); % 0
% dual variable
pi1 = dual(constr('eq1')); % by strong duality, this should be -4, but result given is 4
pi2 = dual(constr('eq2'));
pi3 = dual(constr('eq3'));
pi4 = dual(constr('eq4'));
[dual(constr) p.solveroutput.lambda.ineqlin]

**Comment by yang-au-carre** [comment]
%% variables
y1 = sdpvar(1,1);
y2 = sdpvar(1,1);
%% constraints
constr = [];
constr = constr + [(6*y1+10*y2 <= 2400):'eq1'];
constr = constr + [(8*y1+5*y2<=6400):'eq2'];
constr = constr + [(y1 <= 500):'eq3'];
constr = constr + [(y2 <= 100):'eq4'];
constr = constr + [0<=y1,0<=y2];
w = -24*y1-28*y2;
options=sdpsettings('solver','cplex','savesolveroutput',1);
p=optimize(constr,w,options);
% primal variable
w = value(w);
y1 = value(y1); % 400
y2 = value(y2); % 0
% dual variable
pi1 = dual(constr('eq1')); % by strong duality, this should be -4, but result given is 4
pi2 = dual(constr('eq2'));
pi3 = dual(constr('eq3'));
pi4 = dual(constr('eq4'));
[dual(constr) p.solveroutput.lambda.ineqlin]

**Comment by yang-au-carre** [comment]
The result returned is：

Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de2ae
CPXPARAM_MIP_Display                             1
Tried aggregator 1 time.
LP Presolve eliminated 6 rows and 2 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.00 ticks)

ans =

     4     4
     0     0
     0     0
     0     0
     0     0
    12    12

**Comment by johanlofberg** [comment]
this there is nothing wrong. yalmip returns the cplex dual, and cplex and yalmip have the same sign convention on duals

**Comment by yang-au-carre** [comment]
Thank you for your response, does that mean  cplex gives the wrong dual value? I am totally confused.

**Comment by johanlofberg** [comment]
You seem to think a dual has a predefined sign. The sign of a dual is a convention which has to be specified. YALMIP and cplex and many solver use non-negative duals. You seem to use a convention with negative duals

**Comment by yang-au-carre** [comment]
Actually, this is an example in book "introduction to stochastic programming".  In this case, if the dual is positive, then the strong duality will not hold. Do you have any suggestions to figure out why this happens？

**Comment by johanlofberg** [comment]
A dual for an inequality cannot take both negative and positive values. A dual with such properties is for an equality (your model has an inequality, but you call it eq1, so it looks like you've got something wrong in the model). 

However, that opens up for another issue and that is the fact that duals for equalities is hard to work with when you have a modelling layer in between, as f(x)=g(x) can be seen as f(x)-g(x) and g(x)-f(x)=0 which have have different dual signs, and thus you must know how the modelling layer and the solver converts a model to low-level representation

**Comment by yang-au-carre** [comment]
O, all the constraints are inequalities.
