### ISSUE TITLE
Adding an sdpvar to an empty (double) variable returns empty double variable

### ISSUE THREAD

**Issue by ddlmcp** [yalmip/YALMIP#688]
In the code below, 'b' results in an empty double instead of being equal to 'a':

b = [ ];
a = sdpvar();
b = b + a

This could happen if creating an objective function starting with "Objective = [ ]" and then adding sdpvars to it.

**Comment by johanlofberg** [comment]
No, adding something to an empty should keep it as an empty

`>> b = [ ];
a = 1;
b = b + a

b =

     []`

The correct pattern is to initialize Objective = 0;

**Comment by ddlmcp** [comment]
Oh, ok, this was contrary to my intuition, which was then wrong since Matlab does the same with numbers as you pointed out. 
Thanks
