### ISSUE TITLE
Make degree a method instead of function to avoid nameclash

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#702]

**Comment by johanlofberg** [comment]
But then problems arise when the argument is a constant...

**Comment by PiotrBalik** [comment]
Creating method for doubles is possible: `extras/@double/degree.m`
Feels like an overkill, but I can't think of any other solution

**Comment by johanlofberg** [comment]
yes, but I've always tried to avoid adding overloading of doubles. Don't like that as it is such a universal class, and I bet that would lead to nameclash in some other toolbox
