### ISSUE TITLE
call_mosek_geometric fails with mosek >=9

### ISSUE THREAD

**Issue by lukacsarpad** [yalmip/YALMIP#748]
The function call_mosek_geometric fails with mosek version >=9, due to the deprecation of the function mskgpopt in mosek.

**Comment by johanlofberg** [comment]
Yes, it is a known issue, #594.

**Comment by johanlofberg** [comment]
For the time being, use mosek 8, formulate manually, or simply use 'fmincon-geometric' (GPs are solved surprisingly well with fmincon after YALMIP has sent the convex form, which it does automatically)
