### ISSUE TITLE
Yalmiptest error

### ISSUE THREAD

**Issue by yongp14** [yalmip/YALMIP#811]
When I run yalmiptest on Matlab 2016a, I have the following error:

Undefined function or method 'is' for input arguments of type  'struct'.

export (line 111)
if any(is(F,'uncertain'))

yalmiptest (line 279)
x = sdpvar(2);[p,aux1,aux2,m] = export(x>=0,[],[],[],[],0);

How to tackle this problem?

**Comment by johanlofberg** [comment]
(use the google groups forum for support issues as this site is for bug tracking)

That means you installation is completely broken, i.e. I suspect you cannot even run this and get the expected constraint object

```
>> x = sdpvar(2);x>=0
+++++++++++++++++++++++++++++++++++++++++++++++++++++
|   ID|              Constraint|   Coefficient range|
+++++++++++++++++++++++++++++++++++++++++++++++++++++
|   #1|   Matrix inequality 2x2|              1 to 1|
+++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by yongp14** [comment]
when I run x = sdpvar(2);x>=0 I get:
     clauses: {{1x1 cell}}
       LMIid: 18
    savedata: []
    dualized: 0

Does that mean I should re-install the Matlab?

**Comment by johanlofberg** [comment]
I would make sure I only have one version of YALMIP in the path, and restart MATLAB. Something very weird is going on in your setup. 

If it still doesn't work, you will have to check that you don't have any strange file overloading

```
K>> which lmi -all
C:\work\yalmip\extras\@lmi\lmi.m  % lmi constructor
K>> which constraint -all
C:\work\yalmip\extras\@constraint\constraint.m  % constraint constructor
K>> which class
built-in (C:\Program Files\MATLAB\R2016b\toolbox\matlab\datatypes\class)
```

**Comment by yongp14** [comment]
Many Thanks! I have solved the problem
I delete the path, restart my computer, and add the path. Then it works
It's very weird...
