### ISSUE TITLE
SCIP nl solver not found in YALMIP 

### ISSUE THREAD

**Issue by maolingao** [yalmip/YALMIP#844]
Hi Johan,

I have built scipoptsuite-7.0.1 manually, with no errors. And the cml interaction using scip looks all good. 

However, after adding the <path-to-scip-bin> into Matlab pathdef.m, executing `yalmiptest` in Matlab shows followings. It is strange that only the linear version of scip can be found.

```
+++++++++++++++++++++++++++++++++++++++++++++++
|       Searching for installed solvers       |
+++++++++++++++++++++++++++++++++++++++++++++++
|        Solver|   Version/module|      Status|
+++++++++++++++++++++++++++++++++++++++++++++++
|          SCIP|           linear|       found|
|          SCIP|               nl|   not found|
```

Running the test suggested in https://github.com/yalmip/YALMIP/issues/337 throws errors, probably due to lack of scip nl.

```
sdpvar x y
optimize([x>=0,y>=0,x + y == 1],x-y,sdpsettings('solver','scip','debug',1))

ans = 

  struct with fields:

    yalmipversion: '20200930'
    matlabversion: '9.8.0.1417392 (R2020a) Update 4'
       yalmiptime: 0.0544
       solvertime: 0.0013
             info: 'Unknown error (SCIP-linear)'
          problem: -1
```

To verify that the scip nl is indeed built and available, running the same problem using scip nl in the cml gives success.

```
% simple1.lp
Maximize
 obj: x - y
Subject To
 c1: x + y == 1
Bounds
 x >= 0
 y >= 0
End
```
```
./bin/scip -c "read simple1.lp optimize quit"
SCIP version 7.0.1 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 5.0.1] [GitHash: b41d526acf]
Copyright (C) 2002-2020 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

External codes: 
  Readline EditLine w  GNU library for command line editing (gnu.org/s/readline)
  SoPlex 5.0.1         Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: fcd2a2a5]
  CppAD 20180000.0     Algorithmic Differentiation of C++ algorithms developed by B. Bell (www.coin-or.org/CppAD)
  ZLIB 1.2.11          General purpose compression library by J. Gailly and M. Adler (zlib.net)
  GMP 6.2.0            GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  ZIMPL 3.4.0          Zuse Institute Mathematical Programming Language developed by T. Koch (zimpl.zib.de)
  PaPILO 1.0.1         parallel presolve for integer and linear optimization (https://github.com/lgottwald/PaPILO) [GitHash: 0638fc4]

user parameter file <scip.set> not found - using default parameters


read problem </Users/maolin/workspace/solvers/scip/scipoptsuite-7.0.1/test/simple1.lp>
============

original problem has 2 variables (0 bin, 0 int, 0 impl, 2 cont) and 1 constraints

presolving:
(round 1, fast)       1 del vars, 1 del conss, 0 add conss, 2 chg bounds, 0 chg sides, 0 chg coeffs, 0 upgd conss, 0 impls, 0 clqs
   Deactivated symmetry handling methods, since SCIP was built without symmetry detector (SYM=none).
presolving (2 rounds: 2 fast, 1 medium, 1 exhaustive):
 2 deleted vars, 1 deleted constraints, 0 added constraints, 2 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques
presolved problem has 0 variables (0 bin, 0 int, 0 impl, 0 cont) and 0 constraints
transformed objective value is always integral (scale: 1)
Presolving Time: 0.00

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl. 
t 0.0s|     1 |     0 |     0 |     - | trivial|   0 |   0 |   0 |   0 |   0 |  0 |   0 |   0 | 1.000000e+00 | 1.000000e+00 |   0.00%| unknown

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 0.00
Solving Nodes      : 1
Primal Bound       : +1.00000000000000e+00 (1 solutions)
Dual Bound         : +1.00000000000000e+00
Gap                : 0.00 %
```

My system:
MacOs, BigSur 11.1
Matlab: 9.8.0.1417392 (R2020a) Update 4
YALMIP: 20200930, 
commit aa0b53546116e568f0958d3d51311c8f2f9eca36 (HEAD -> master, tag: R20200930, upstream/master, origin/master)
SCIP: scipoptsuite-7.0.1, compiled by cmake.

What could hinder the detection of scip nl in Matlab then? thanks for your help.

**Comment by johanlofberg** [comment]
YaLMIP looks for the file opti_scipnl. If you've compiled without opti, you don't have that file. Also if you don't use opti, have you really compiled a matlab binary for linear scip?

**Comment by maolingao** [comment]
> YaLMIP looks for the file opti_scipnl. If you've compiled without opti, you don't have that file.

Thanks for the hint. I don't think I did anything related to OPTI, because scip and yalmip didn't complain about it.

> Also if you don't use opti, have you really compiled a matlab binary for linear scip?

what do you mean by "compelling a Matlab binary for linear scip" exactly? 

If you mean "compiling SCIP binary from its source code", yes I did it by CMake, but I didn't specify a built for linear scip only. It also explains that scip is correct compiled, b/c it can solve in cml.

Btw, below is the cml logs after running CMake for compiling scip, it is probably correct that it doesn't looking for OPTI at all.

```
-- The following OPTIONAL packages have been found:

 * Threads
 * BLAS
 * Readline
 * PAPILO
 * ZIMPL
 * ZLIB
 * PkgConfig

-- The following REQUIRED packages have been found:

 * BISON
 * FLEX
 * TBB
 * GMP
 * SCIP
 * SOPLEX
 * boost_headers (required version == 1.73.0)
 * Boost

-- The following OPTIONAL packages have not been found:

 * Quadmath
 * IPOPT (required version >= 3.12.0)
 * CRITERION
 * GSL (required version >= 2.0)
 * CLIQUER
 * HMETIS
 * BLISS

-- Configuring done
-- Generating done
```

Probably I am missing some steps on generating opti_scipnl, do you know how to generate/where to find it?

**Comment by johanlofberg** [comment]
YALMIP needs a matlab interface to scip (which opti supplies). I don't think you have that (the fact that scip is claimed detected is probably because you have a scip.exe or something like that in your path (check with "which scip -all"). If you try to use scip from matlab/yalmip I think you will see that it fails)

**Comment by maolingao** [comment]
you are right, `which scip -all` fails in Matlab.

I've taken a look in OPTI and it seems that it is predominantly designed in Windows, and it requires some manual effort to make it work on Mac. 

Do you know whether it supports Mac at all? any good references to guide through the process?

**Comment by johanlofberg** [comment]
which scip -all  canot fail, but it will reveal that you don't have a mex version

I've not heard of anyone managing to port opti to linux or mac

**Comment by maolingao** [comment]
yeah, the command itself works, just no mex file found :D

Thanks for the answer, it spares time. 

The missing support of OPTI on Mac or Linux actually makes it hard to use yalmip with SCIP (One can opt to other solvers such as Gurobi, but SCIP is open-source.) And btw SCIP is out-of-maintance, it is likely that it will not work on windows as well in the future. Is there any plan to make yalmip work with SCIP on Mac/Linux?

**Comment by johanlofberg** [comment]
YALMIP assumes that there are interfaces available, so it is up to the scip community at large to make scip available in MATLAB for that to happen

**Comment by maolingao** [comment]
thanks very much for your help, Johan!
