### ISSUE TITLE
Support solving problems via a call to NEOS Server

### ISSUE THREAD

**Issue by tholden** [yalmip/YALMIP#845]
It would be great if YALMIP would also support using remote calls to [NEOS Server](https://neos-server.org/neos/) for solving optimization problems.

NEOS [provides a Java client](https://neos-server.org/neos/downloads.html), which would be one route to implement this, though it's also possible to send and receive RPC requests directly from MATLAB.

This would enable users without a locally installed solver to still solve problems.

**Comment by naivej** [comment]
That is something I also love to have
