### ISSUE TITLE
Mosek is removed form lp solver candidate when using bmibnb

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#851]

**Comment by pbpf** [comment]
顶顶顶
----- 原始邮件 -----
发件人：Johan Löfberg <notifications@github.com>
收件人：yalmip/YALMIP <YALMIP@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re: [yalmip/YALMIP] Mosek is removed form lp solver candidate when using bmibnb (#851)
日期：2021年02月26日 04点58分


Closed #851 via 562b5d7.

&mdash;
