### ISSUE TITLE
Parsing error with SDPT3

### ISSUE THREAD

**Issue by mfry90** [yalmip/YALMIP#871]
An SDP which solves in `mosek` fails to parse in `sdpt3`.  I'm not sure if this is a problem with the sdpt3 solver itself, or with the function `callsdpt34`.  See example code below:
```
[ct, obj] = loadsdpafile('failed_sdp.dat-s.zip')
ops = sdpsettings('solver', 'mosek', 'debug', 1);
optimize(ct, obj, ops) %Works fine
ops.solver = 'sdpt3';
optimize(ct, obj, ops) %Fails
```

[failed_sdp.dat-s.zip](https://github.com/yalmip/YALMIP/files/6361328/failed_sdp.dat-s.zip)

**Comment by johanlofberg** [comment]
SDPT3 does not like trivially over-parameterized models and refuses to solve them. Similar to this 

>> sdpvar x y
>> optimize([x+y >= 0],x+y,sdpsettings('solver','sdpt3'))
