### ISSUE TITLE
'yalmiptime' keeps increasing when YALMIP is called for many times

### ISSUE THREAD

**Issue by shishouyuan** [yalmip/YALMIP#875]
Hello,
I use YALMIP in a way that a simple problem needs to be solved many times with different parameters. In each iteration, variables and constraints are recreated since I don't know how to change the parameters after the problem is built. I found that as the process goes '_yalmiptime_' keeps increasing, roughly from 40ms at the beginning to 100ms after 1000 iterations and can go to several seconds if the iteration keeps on .
I found that there is a persistent variable '_internal_sdpvarstate.monomtable_' in '_yalmip.m_' whose size becomes very large in the iterations. In '_times.m_', '_monomtable_' is concatenated with previous values and assigned to '_internal_sdpvarstate.monomtable_' by calling  '_yalmip.m_', and the concatenation takes a long time when '_monomtable_' is very large. I temporarily solved this problem by calling '_clear functions_' to clear the persistent variable in '_yalmip.m_'.
Could you help me get the right way to handle this problem? I'm new to YALMIP and I can't find the answer in the documents. 
Thanks.

**Comment by johanlofberg** [comment]
when you start a model from scratch, you always start with yalmip('clear')

When coding, a typical mistake is to create more and more variables internally
```
for loop
x = sdpvar...
setup constraints
solve
end
```

instead of defining them once

```
x = sdpvar...
for loop
setup constraints
solve
end
```

Since this is not a bug, I recommend you to post questions or general discussion on the YALMIP Google groups form

**Comment by shishouyuan** [comment]
Thank you so much.

> when you start a model from scratch, you always start with yalmip('clear')
> 
> When coding, a typical mistake is to create more and more variables internally
> 
> ```
> for loop
> x = sdpvar...
> setup constraints
> solve
> end
> ```
> 
> instead of defining them once
> 
> ```
> x = sdpvar...
> for loop
> setup constraints
> solve
> end
> ```
> 
> Since this is not a bug, I recommend you to post questions or general discussion on the YALMIP Google groups form

Thank you so much.

**Comment by shishouyuan** [comment]
Hi, Johan. Would you consider introducing yalmip('clear') in the 'Getting started' part of the tutorials? I think it's important for the beginner to know this. Thanks.

**Comment by johanlofberg** [comment]
Good idea, will do!
