### ISSUE TITLE
Initial guess not used in first call to optimizer when using IPOPT

### ISSUE THREAD

**Issue by ddlmcp** [yalmip/YALMIP#925]
Example:
sdpvar x y
assign(x,10);
opt = optimizer([-1<=x<=1],y*(x-0.5)^3,sdpsettings('solver','ipopt','usex0',1),{y},{x});
sol = opt(1);

Not sure if this is related to #633, but using when IPOPT and optimizer, it seems like in the first call to the optimizer the initial guess x0 is always considered as an array of 0s, regardless of using usex0=1 and assign(x,some_x_value). This can be seen by stepping through code in callipopt.m. Subsequent calls to the opt optimizer object do seem to correctly use the previous solution as an initial guess.

**Comment by johanlofberg** [comment]
As intended. Too much going on so yalmip cannot track the map from initial  user model down to the model which is solved.
