### ISSUE TITLE
MAX fails on ndsdpvar

### ISSUE THREAD

**Issue by johanlofberg** [yalmip/YALMIP#95]
```
x = sdpvar(2,3,4);
y = max(x(1,:,:))
```

**Comment by johanlofberg** [comment]
Still fails

`max(P(1,:,:))`

**Comment by PiotrBalik** [comment]
Here is a promising fix:
[max.txt](https://github.com/yalmip/YALMIP/files/7027306/max.txt)
[testmax.txt](https://github.com/yalmip/YALMIP/files/7027307/testmax.txt)

Behavior is consistent with matlab's for doubles

*For some reason code doesn't format well, attached files

**Comment by johanlofberg** [comment]
Are you familiar enough with git to do a pull request directly to develop?
