### ISSUE TITLE
sdpvar * sdpvar: superfast quadratic multiplication fails

### ISSUE THREAD

**Issue by denisrosset** [yalmip/YALMIP#984]
The following code fails on the latest YALMIP 270c2814ce2b45b8d86d7ef85ea432b8ed49ee4f :
```
t = sdpvar;
t * [t;t]
```
with the error:
```
Error using  *  (line 520)
Error using horzcat
Dimensions of arrays being concatenated are
not consistent. 
520             error(lasterr)
```

As a workaround, commenting out lines 100-101 (and thus disable super_fast_quadratic_multiplication) removes the problem.

**Comment by johanlofberg** [comment]
Congratulations, you just won the "find the oldest core bug".  It was not introduced in the commit you referenced. It is in the core already in the oldest release tag I have in git (august 2012).

Will fix of course!
