### ISSUE TITLE
protect discovery method from sending errors

### ISSUE THREAD

**Issue by jdbancal** [yalmip/YALMIP#985]
The way that yalmip checks for the existence of some external components currently is based on a `try`/`catch` mechanism as in
```
try
    libAvalue = libA;
catch
    libAvalue = [];
end
```
If `libA` is not present on the system, this simply sets `libAvalue` to an empty.

The nice part about this is that it is quite a robust mechanism. One shortcoming with this, however, is that it actually creates logical `errors` along what is actually a normal execution of the code. This can confuse the debugger. For instance, running a code with `dbstop if caught error` will typically stop tens of times every time `sdpsettings` is run. `sdpvar` also contains such mechanism.

Would it be possible to combine the existing approach with a call to the `exist` function to avoid calling a function that does not exist (and hence avoid throwing expected errors if possible)?

**Comment by johanlofberg** [comment]
running exist can be super slow on some systems

**Comment by PiotrBalik** [comment]
`exist` by itself searches everywhere (files, directories) until it finds given argument. `'var'` as additional parameter helps. Here is small benchmark:
```matlab
function a=yalmtry(x)
tic
for i=1:1000
if exist('x'),    a=x;
else,    a=[];  end
end
toc

tic
for i=1:1000
if exist('x','var'),    a=x;
else,    a=[];   end
end
toc

tic
for i=1:1000
try,    a=x;
catch,    a=[];   end
end
toc
```

And results on my setup:
```
>> yalmtry
Elapsed time is 1.819370 seconds.
Elapsed time is 0.016033 seconds.
Elapsed time is 0.239590 seconds.

ans =

     []

>> yalmtry(1)
Elapsed time is 0.016017 seconds.
Elapsed time is 0.017336 seconds.
Elapsed time is 0.000865 seconds.

ans =

     1
```
@jdbancal if you want convenient debugging, use the improved `exist`
